// PezMax-One build script
// Only compiles Windows resources (.rc → embedded icon). Linux Wayland protocol
// bindings are generated by `wayland-scanner` proc-macros in source, not here.

fn main() {
    #[cfg(target_os = "windows")]
    {
        let _ = embed_resource::compile("build/windows/icon.rc", embed_resource::NONE);
    }
}